import 'package:food_app/modals/productModal.dart';

class global {
  static bool data = false;
  static List<Product> products = [
    Product(
      id: 1,
      name: "Avocado Salad",
      price: 50,
      image: "assets/images/food1.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 2,
      name: "Monsoon Salad",
      price: 150,
      image: "assets/images/food2.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 3,
      name: "Royal Salad",
      price: 250,
      image: "assets/images/food3.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 4,
      name: "Fruits Salad",
      price: 100,
      image: "assets/images/food4.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 5,
      name: "Loyal Salad",
      price: 80,
      image: "assets/images/food5.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 6,
      name: "Basic Salad",
      price: 70,
      image: "assets/images/food6.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 7,
      name: "All Fruits",
      price: 170,
      image: "assets/images/fruit1.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 8,
      name: "Mi Fruits",
      price: 120,
      image: "assets/images/fruit2.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 9,
      name: "Unique Fruits",
      price: 210,
      image: "assets/images/fruit3.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 10,
      name: "All Grocery",
      price: 105,
      image: "assets/images/gro1.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 11,
      name: "Mix Grocery",
      price: 125,
      image: "assets/images/gro2.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 12,
      name: "Basic Grocery",
      price: 135,
      image: "assets/images/gro3.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 13,
      name: "Crude Grocery",
      price: 225,
      image: "assets/images/gro4.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 14,
      name: "All Veges",
      price: 425,
      image: "assets/images/veg2.png",
      quantity: 0,
      like: "false",
    ),
    Product(
      id: 15,
      name: "Mix Veges",
      price: 585,
      image: "assets/images/veg3.png",
      quantity: 0,
      like: "false",
    ),
  ];
}


